### ISSUE TITLE
로그인 유지 불안정성

### ISSUE THREAD

**Issue by sesangbit56** [sesangbit56/schoolmate#22]
페이지 새로고침시 로그인 유지가 엉뚱하게 되는 매우매우 심각한 버그가 있음...

**Comment by holy-water** [comment]
1. 새로 고침 시 로그인 유지가 되지 않는 현상
- homeRoutes 함수에서 session 초기화 로직 제거

2. (위 내용 수정 후) 세션 삭제 후 새로 고침 시 로그인 유지가 되는 현상
- /login (GET) 함수에서 jwt.verify 오류 (해당 오류로 이후 로직이 실행되고 있지 않네요.)

- 이 다음부터는 여러 방법이 있을 거 같은데 토큰이 없거나 에러가 발생하는 경우 session을 초기화 하고 response.login 값에 상관없이 /signIn 호출해서 해당 session에 담긴 값으로 렌더링 해주면 될 거 같습니다.
- 아니면 추후 로그아웃까지 생각해서 response.login 값으로 분기해서 /signOut(가칭) 호출해도 좋을 거 같습니다.

**Comment by sesangbit56** [comment]
jwt 토큰 인증 과정에서 오류가 나는 부분 확인 완료했습니다.
다만, 위에서 말씀해주신 방법으로는 새로고침을 2번 해야 정상적으로 돌아오는 문제가 발생하는걸 확인했습니다....

아예 localStorage가 아니라 cookie를 사용하는 방법도 고려해뵈야 할 듯 합니다...

**Comment by sesangbit56** [comment]
데이터 수정 방식 cookie로 전환 후 성공적으로 수행되는 걸 확인했습니다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!111
와왕아아아앙ㅇ아ㅏㅏㅏ111!!!!!ㄱㄱㄱ!!!!1!!
